spring:
  application.name:
    barobaedal
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
    jsp:
      init-parameters:
        development: true
  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/d_project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: hoowave
    password:

app:
  upload:
    dir: src/main/webapp/upload